/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HelpCenterPage = {
  _id: string;
  _type: "helpCenterPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: LocalizedString;
  heroLabelRight?: LocalizedString;
  heroHeadline?: LocalizedString;
  heroHeadlineAccent?: LocalizedString;
  heroSubtitle?: LocalizedText;
  stats?: Array<{
    value?: string;
    label?: LocalizedString;
    icon?: string;
    _key: string;
  }>;
  channelsLabel?: LocalizedString;
  channelsHeadline?: LocalizedString;
  channels?: Array<{
    title?: LocalizedString;
    desc?: LocalizedText;
    action?: string;
    href?: string;
    icon?: string;
    _key: string;
  }>;
  formLabel?: LocalizedString;
  formHeadline?: LocalizedString;
  formDescription?: LocalizedText;
  contactEmail?: string;
  contactPhone?: string;
  ctaHeadline?: LocalizedString;
  ctaDescription?: LocalizedText;
};

export type LocalizedText = {
  _type: "localizedText";
  en?: string;
  sv?: string;
};

export type LocalizedString = {
  _type: "localizedString";
  en?: string;
  sv?: string;
};

export type AiAssistantPage = {
  _id: string;
  _type: "aiAssistantPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: LocalizedString;
  heroLabelRight?: LocalizedString;
  heroHeadline?: LocalizedString;
  heroHeadlineAccent?: LocalizedString;
  heroSubtitle?: LocalizedText;
  botTitle?: LocalizedString;
  botDescription?: LocalizedText;
  botStatus?: LocalizedString;
  botLaunchDate?: LocalizedString;
  featuresLabel?: LocalizedString;
  featuresHeadline?: LocalizedString;
  features?: Array<{
    title?: LocalizedString;
    desc?: LocalizedText;
    icon?: string;
    _key: string;
  }>;
  ctaHeadline?: LocalizedString;
  ctaDescription?: LocalizedText;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: LocalizedString;
  description?: LocalizedText;
  faqs?: Array<{
    question?: LocalizedString;
    answer?: LocalizedText;
    _key: string;
  }>;
};

export type WebshopPage = {
  _id: string;
  _type: "webshopPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: LocalizedString;
  description?: LocalizedText;
  merchTitle?: LocalizedString;
  merchPendingMessage?: LocalizedText;
  quoteTitle?: LocalizedString;
  quoteButton?: LocalizedString;
};

export type CareersPage = {
  _id: string;
  _type: "careersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: LocalizedString;
  heroLabelRight?: LocalizedString;
  headline?: LocalizedString;
  description?: LocalizedText;
  perks?: Array<{
    title?: LocalizedString;
    desc?: LocalizedText;
    icon?: string;
    _key: string;
  }>;
  openApplicationTitle?: LocalizedString;
  openApplicationDesc?: LocalizedText;
  formHeadline?: LocalizedString;
  successTitle?: LocalizedString;
  successDesc?: LocalizedText;
  ctaHeadline?: LocalizedString;
  ctaDescription?: LocalizedText;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type LeadershipPage = {
  _id: string;
  _type: "leadershipPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: LocalizedString;
  description?: LocalizedText;
  teamMembers?: Array<{
    name?: string;
    role?: LocalizedString;
    bio?: LocalizedText;
    linkedin?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  sectionLabel?: LocalizedString;
  sectionLabelRight?: LocalizedString;
  ctaHeadline?: LocalizedString;
  ctaDescription?: LocalizedText;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type VipPage = {
  _id: string;
  _type: "vipPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: LocalizedString;
  heroLabelRight?: LocalizedString;
  heroHeadline?: LocalizedString;
  heroHeadlineAccent?: LocalizedString;
  heroStats?: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }>;
  heroAnchorText?: LocalizedString;
  heroIntroText?: LocalizedText;
  videoLabel?: LocalizedString;
  videoText?: LocalizedString;
  manifestoLabel?: LocalizedString;
  manifestoHeadline?: LocalizedString;
  manifestoHeadlineAccent?: LocalizedString;
  manifestoQuote?: LocalizedText;
  manifestoBody1?: LocalizedText;
  manifestoBody2?: LocalizedText;
  manifestoMotto?: LocalizedString;
  manifestoStats?: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }>;
  tiersLabel?: LocalizedString;
  tiersLabelRight?: LocalizedString;
  tiersHeadline?: LocalizedString;
  tiersDescription?: LocalizedText;
  tierCards?: Array<{
    name?: LocalizedString;
    badge?: LocalizedString;
    price?: LocalizedString;
    priceSub?: LocalizedString;
    features?: Array<
      {
        _key: string;
      } & LocalizedString
    >;
    cta?: LocalizedString;
    highlight?: boolean;
    _key: string;
  }>;
  stepsLabel?: LocalizedString;
  stepsLabelRight?: LocalizedString;
  stepsHeadline?: LocalizedString;
  steps?: Array<{
    step?: string;
    title?: LocalizedString;
    description?: LocalizedText;
    _key: string;
  }>;
  ctaCard1Title?: LocalizedString;
  ctaCard1Desc?: LocalizedString;
  ctaCard2Title?: LocalizedString;
  ctaCard2Headline?: LocalizedString;
  ctaCard2Sub?: LocalizedString;
};

export type SecurityPage = {
  _id: string;
  _type: "securityPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: LocalizedString;
  heroLabelRight?: LocalizedString;
  heroBadge?: LocalizedString;
  heroHeadline?: LocalizedString;
  heroHeadlineAccent?: LocalizedString;
  heroSubtitle?: LocalizedText;
  pillarsLabel?: LocalizedString;
  pillarsHeadline?: LocalizedString;
  pillarsHeadlineAccent?: LocalizedString;
  pillarCards?: Array<{
    title?: LocalizedString;
    description?: LocalizedText;
    icon?:
      | "lock"
      | "server"
      | "fileCheck"
      | "userCheck"
      | "eye"
      | "alertTriangle";
    _key: string;
  }>;
  complianceLabel?: LocalizedString;
  complianceHeadline?: LocalizedString;
  complianceHeadlineAccent?: LocalizedString;
  complianceSections?: Array<{
    category?: LocalizedString;
    items?: Array<
      {
        _key: string;
      } & LocalizedString
    >;
    _key: string;
  }>;
  rightsLabel?: LocalizedString;
  rightsHeadline?: LocalizedString;
  rightsHeadlineAccent?: LocalizedString;
  rightsIntro?: LocalizedText;
  rightsList?: Array<{
    right?: LocalizedString;
    description?: LocalizedText;
    _key: string;
  }>;
  dpoTitle?: LocalizedString;
  dpoSubtitle?: LocalizedString;
  dpoDescription?: LocalizedText;
  dpoEmail?: string;
  ctaHeadline?: LocalizedString;
  ctaDescription?: LocalizedText;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: LocalizedString;
  heroLabelRight?: LocalizedString;
  heroHeadline?: LocalizedString;
  heroHeadlineAccent?: LocalizedString;
  heroHeadlineLine3?: LocalizedString;
  heroSubtitle?: LocalizedText;
  stats?: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }>;
  storyLabel?: LocalizedString;
  storyHeadline?: LocalizedString;
  storyHeadlineAccent?: LocalizedString;
  storyQuote?: LocalizedText;
  storyBody1?: LocalizedText;
  storyBody2?: LocalizedText;
  valuesLabel?: LocalizedString;
  valuesHeadline?: LocalizedString;
  valuesHeadlineAccent?: LocalizedString;
  valueCards?: Array<{
    title?: LocalizedString;
    description?: LocalizedText;
    icon?: "heart" | "zap" | "globe" | "shield";
    _key: string;
  }>;
  teamLabel?: LocalizedString;
  teamIntro?: LocalizedText;
  teamMembers?: Array<{
    name?: string;
    role?: LocalizedString;
    bio?: LocalizedText;
    linkedin?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    initials?: string;
    _key: string;
  }>;
  ctaHeadline?: LocalizedString;
  ctaDescription?: LocalizedText;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navLinks?: Array<{
    label?: LocalizedString;
    href?: string;
    _key: string;
  }>;
  navCta?: LocalizedString;
  heroBadge?: LocalizedString;
  heroHeadline?: LocalizedString;
  heroHeadlineAccent?: LocalizedString;
  heroSubheadline?: LocalizedText;
  heroCta1?: LocalizedString;
  heroCta2?: LocalizedString;
  videoLabel?: LocalizedString;
  videoHeadline?: LocalizedString;
  videoHeadlineAccent?: LocalizedString;
  videoDescription?: LocalizedText;
  servicesLabel?: LocalizedString;
  servicesLabelRight?: LocalizedString;
  servicesHeadline?: LocalizedString;
  servicesDescription?: LocalizedText;
  servicesStats?: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }>;
  serviceCards?: Array<{
    title?: LocalizedString;
    desc?: LocalizedText;
    icon?: "mic" | "users" | "glass" | "globe";
    _key: string;
  }>;
  servicesFullserviceTitle?: LocalizedString;
  servicesFullserviceDesc?: LocalizedText;
  flagsLabel?: LocalizedString;
  flagsLabelRight?: LocalizedString;
  flagsHeadline?: LocalizedString;
  flagsDescription?: LocalizedText;
  flagsMetrics?: Array<{
    value?: number;
    stringValue?: string;
    suffix?: string;
    label?: LocalizedString;
    _key: string;
  }>;
  casesLabel?: LocalizedString;
  casesLabelRight?: LocalizedString;
  casesHeadline?: LocalizedString;
  casesDescription?: LocalizedText;
  caseCards?: Array<{
    client?: string;
    event?: LocalizedString;
    description?: LocalizedText;
    guests?: string;
    location?: LocalizedString;
    duration?: LocalizedString;
    _key: string;
  }>;
  casesCta?: LocalizedString;
  ctaLabel?: LocalizedString;
  ctaLabelRight?: LocalizedString;
  ctaHeadline?: LocalizedString;
  ctaSubheadline?: LocalizedString;
  ctaCard1Title?: LocalizedString;
  ctaCard1Desc?: LocalizedString;
  ctaCard2Title?: LocalizedString;
  ctaCard2Headline?: LocalizedString;
  ctaCard2Sub?: LocalizedString;
  newsletterHeadline?: LocalizedString;
  newsletterDescription?: LocalizedText;
  newsletterPlaceholder?: LocalizedString;
  newsletterButton?: LocalizedString;
  aboutLabel?: LocalizedString;
  aboutHeadline?: LocalizedString;
  aboutHeadlineAccent?: LocalizedString;
  aboutQuote?: LocalizedText;
  aboutBody?: LocalizedText;
  aboutBody2?: LocalizedText;
  aboutMotto?: LocalizedString;
  aboutStats?: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }>;
  aboutTeamLabel?: LocalizedString;
  aboutTeamIntro?: LocalizedText;
  aboutTeam?: Array<{
    name?: string;
    role?: LocalizedString;
    bio?: LocalizedText;
    linkedin?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    initials?: string;
    _key: string;
  }>;
  faqHeadline?: LocalizedString;
  faqDescription?: LocalizedText;
  faqItems?: Array<{
    question?: LocalizedString;
    answer?: LocalizedText;
    _key: string;
  }>;
  faqCtaText?: LocalizedString;
  faqCtaLink?: LocalizedString;
  formBadge?: LocalizedString;
  formHeadline?: LocalizedString;
  formHeadlineAccent?: LocalizedString;
  formDescription?: LocalizedText;
  formButton?: LocalizedString;
  formDisclaimer?: LocalizedString;
  footerBrandDesc?: LocalizedText;
  footerSocialLabel?: LocalizedString;
  footerNewsletterDesc?: LocalizedText;
  footerCtaTitle?: LocalizedString;
  footerCtaDesc?: LocalizedText;
  footerColumns?: Array<{
    title?: LocalizedString;
    links?: Array<{
      label?: LocalizedString;
      href?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  exitLabel?: LocalizedString;
  exitHeadline?: LocalizedString;
  exitHeadlineAccent?: LocalizedString;
  exitDescription?: LocalizedText;
  exitButton?: LocalizedString;
  exitPrivacy?: LocalizedText;
  globeBadge?: LocalizedString;
  globeHeadline?: LocalizedString;
  globeHeadlineAccent?: LocalizedString;
  globeDescription?: LocalizedText;
  webshopLabel?: LocalizedString;
  webshopLabelRight?: LocalizedString;
  webshopHeadline?: LocalizedString;
  webshopHeadlineAccent?: LocalizedString;
  webshopDescription?: LocalizedText;
  webshopComingSoonTitle?: LocalizedString;
  webshopComingSoonDesc?: LocalizedText;
  webshopCtaText?: LocalizedString;
  videoBottomLabel?: LocalizedString;
  videoBottomText?: LocalizedString;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | HelpCenterPage
  | LocalizedText
  | LocalizedString
  | AiAssistantPage
  | FaqPage
  | WebshopPage
  | CareersPage
  | SanityImageAssetReference
  | LeadershipPage
  | SanityImageCrop
  | SanityImageHotspot
  | VipPage
  | SecurityPage
  | AboutPage
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homePage"][0]{    // Navbar    navLinks, navCta,    // Hero    heroBadge, heroHeadline, heroHeadlineAccent, heroSubheadline,    heroCta1, heroCta2,    // Video    videoLabel, videoHeadline, videoHeadlineAccent, videoDescription,    // Services    servicesLabel, servicesLabelRight, servicesHeadline, servicesDescription,    servicesStats, serviceCards, servicesFullserviceTitle, servicesFullserviceDesc,    // Country Flags    flagsLabel, flagsLabelRight, flagsHeadline, flagsDescription,    // Case Stories    casesLabel, casesLabelRight, casesHeadline, casesDescription,    caseCards, casesCta,    // CTA    ctaLabel, ctaLabelRight, ctaHeadline, ctaSubheadline,    ctaCard1Title, ctaCard1Desc, ctaCard2Title, ctaCard2Headline, ctaCard2Sub,    // Newsletter    newsletterHeadline, newsletterDescription, newsletterPlaceholder, newsletterButton,    // About    aboutLabel, aboutHeadline, aboutHeadlineAccent, aboutQuote, aboutBody, aboutBody2, aboutMotto, aboutStats,    aboutTeamLabel, aboutTeamIntro, aboutTeam,    // FAQ    faqHeadline, faqDescription, faqItems, faqCtaText, faqCtaLink,    // Request Form    formBadge, formHeadline, formHeadlineAccent, formDescription,    formButton, formDisclaimer,    // Footer    footerBrandDesc, footerSocialLabel, footerNewsletterDesc,    footerCtaTitle, footerCtaDesc, footerColumns,    // Exit Intent    exitLabel, exitHeadline, exitHeadlineAccent, exitDescription,    exitButton, exitPrivacy,    // Globe    globeBadge, globeHeadline, globeHeadlineAccent, globeDescription,    // Webshop Teaser    webshopLabel, webshopLabelRight, webshopHeadline, webshopHeadlineAccent,    webshopDescription, webshopComingSoonTitle, webshopComingSoonDesc, webshopCtaText,    // Video overlay text    videoBottomLabel, videoBottomText  }
export type HOMEPAGE_QUERY_RESULT = {
  navLinks: Array<{
    label?: LocalizedString;
    href?: string;
    _key: string;
  }> | null;
  navCta: LocalizedString | null;
  heroBadge: LocalizedString | null;
  heroHeadline: LocalizedString | null;
  heroHeadlineAccent: LocalizedString | null;
  heroSubheadline: LocalizedText | null;
  heroCta1: LocalizedString | null;
  heroCta2: LocalizedString | null;
  videoLabel: LocalizedString | null;
  videoHeadline: LocalizedString | null;
  videoHeadlineAccent: LocalizedString | null;
  videoDescription: LocalizedText | null;
  servicesLabel: LocalizedString | null;
  servicesLabelRight: LocalizedString | null;
  servicesHeadline: LocalizedString | null;
  servicesDescription: LocalizedText | null;
  servicesStats: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }> | null;
  serviceCards: Array<{
    title?: LocalizedString;
    desc?: LocalizedText;
    icon?: "glass" | "globe" | "mic" | "users";
    _key: string;
  }> | null;
  servicesFullserviceTitle: LocalizedString | null;
  servicesFullserviceDesc: LocalizedText | null;
  flagsLabel: LocalizedString | null;
  flagsLabelRight: LocalizedString | null;
  flagsHeadline: LocalizedString | null;
  flagsDescription: LocalizedText | null;
  casesLabel: LocalizedString | null;
  casesLabelRight: LocalizedString | null;
  casesHeadline: LocalizedString | null;
  casesDescription: LocalizedText | null;
  caseCards: Array<{
    client?: string;
    event?: LocalizedString;
    description?: LocalizedText;
    guests?: string;
    location?: LocalizedString;
    duration?: LocalizedString;
    _key: string;
  }> | null;
  casesCta: LocalizedString | null;
  ctaLabel: LocalizedString | null;
  ctaLabelRight: LocalizedString | null;
  ctaHeadline: LocalizedString | null;
  ctaSubheadline: LocalizedString | null;
  ctaCard1Title: LocalizedString | null;
  ctaCard1Desc: LocalizedString | null;
  ctaCard2Title: LocalizedString | null;
  ctaCard2Headline: LocalizedString | null;
  ctaCard2Sub: LocalizedString | null;
  newsletterHeadline: LocalizedString | null;
  newsletterDescription: LocalizedText | null;
  newsletterPlaceholder: LocalizedString | null;
  newsletterButton: LocalizedString | null;
  aboutLabel: LocalizedString | null;
  aboutHeadline: LocalizedString | null;
  aboutHeadlineAccent: LocalizedString | null;
  aboutQuote: LocalizedText | null;
  aboutBody: LocalizedText | null;
  aboutBody2: LocalizedText | null;
  aboutMotto: LocalizedString | null;
  aboutStats: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }> | null;
  aboutTeamLabel: LocalizedString | null;
  aboutTeamIntro: LocalizedText | null;
  aboutTeam: Array<{
    name?: string;
    role?: LocalizedString;
    bio?: LocalizedText;
    linkedin?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    initials?: string;
    _key: string;
  }> | null;
  faqHeadline: LocalizedString | null;
  faqDescription: LocalizedText | null;
  faqItems: Array<{
    question?: LocalizedString;
    answer?: LocalizedText;
    _key: string;
  }> | null;
  faqCtaText: LocalizedString | null;
  faqCtaLink: LocalizedString | null;
  formBadge: LocalizedString | null;
  formHeadline: LocalizedString | null;
  formHeadlineAccent: LocalizedString | null;
  formDescription: LocalizedText | null;
  formButton: LocalizedString | null;
  formDisclaimer: LocalizedString | null;
  footerBrandDesc: LocalizedText | null;
  footerSocialLabel: LocalizedString | null;
  footerNewsletterDesc: LocalizedText | null;
  footerCtaTitle: LocalizedString | null;
  footerCtaDesc: LocalizedText | null;
  footerColumns: Array<{
    title?: LocalizedString;
    links?: Array<{
      label?: LocalizedString;
      href?: string;
      _key: string;
    }>;
    _key: string;
  }> | null;
  exitLabel: LocalizedString | null;
  exitHeadline: LocalizedString | null;
  exitHeadlineAccent: LocalizedString | null;
  exitDescription: LocalizedText | null;
  exitButton: LocalizedString | null;
  exitPrivacy: LocalizedText | null;
  globeBadge: LocalizedString | null;
  globeHeadline: LocalizedString | null;
  globeHeadlineAccent: LocalizedString | null;
  globeDescription: LocalizedText | null;
  webshopLabel: LocalizedString | null;
  webshopLabelRight: LocalizedString | null;
  webshopHeadline: LocalizedString | null;
  webshopHeadlineAccent: LocalizedString | null;
  webshopDescription: LocalizedText | null;
  webshopComingSoonTitle: LocalizedString | null;
  webshopComingSoonDesc: LocalizedText | null;
  webshopCtaText: LocalizedString | null;
  videoBottomLabel: LocalizedString | null;
  videoBottomText: LocalizedString | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{    // Hero    heroLabel, heroLabelRight, heroHeadline, heroHeadlineAccent, heroHeadlineLine3, heroSubtitle,    // Stats    stats,    // Story    storyLabel, storyHeadline, storyHeadlineAccent, storyQuote, storyBody1, storyBody2,    // Values    valuesLabel, valuesHeadline, valuesHeadlineAccent, valueCards,    // Team    teamLabel, teamIntro, teamMembers,    // CTA    ctaHeadline, ctaDescription  }
export type ABOUT_PAGE_QUERY_RESULT = {
  heroLabel: LocalizedString | null;
  heroLabelRight: LocalizedString | null;
  heroHeadline: LocalizedString | null;
  heroHeadlineAccent: LocalizedString | null;
  heroHeadlineLine3: LocalizedString | null;
  heroSubtitle: LocalizedText | null;
  stats: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }> | null;
  storyLabel: LocalizedString | null;
  storyHeadline: LocalizedString | null;
  storyHeadlineAccent: LocalizedString | null;
  storyQuote: LocalizedText | null;
  storyBody1: LocalizedText | null;
  storyBody2: LocalizedText | null;
  valuesLabel: LocalizedString | null;
  valuesHeadline: LocalizedString | null;
  valuesHeadlineAccent: LocalizedString | null;
  valueCards: Array<{
    title?: LocalizedString;
    description?: LocalizedText;
    icon?: "globe" | "heart" | "shield" | "zap";
    _key: string;
  }> | null;
  teamLabel: LocalizedString | null;
  teamIntro: LocalizedText | null;
  teamMembers: Array<{
    name?: string;
    role?: LocalizedString;
    bio?: LocalizedText;
    linkedin?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    initials?: string;
    _key: string;
  }> | null;
  ctaHeadline: LocalizedString | null;
  ctaDescription: LocalizedText | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: SECURITY_PAGE_QUERY
// Query: *[_type == "securityPage"][0]{    // Hero    heroLabel, heroLabelRight, heroBadge, heroHeadline, heroHeadlineAccent, heroSubtitle,    // Pillars    pillarsLabel, pillarsHeadline, pillarsHeadlineAccent, pillarCards,    // Compliance    complianceLabel, complianceHeadline, complianceHeadlineAccent, complianceSections,    // Rights    rightsLabel, rightsHeadline, rightsHeadlineAccent, rightsIntro, rightsList,    // DPO    dpoTitle, dpoSubtitle, dpoDescription, dpoEmail,    // CTA    ctaHeadline, ctaDescription  }
export type SECURITY_PAGE_QUERY_RESULT = {
  heroLabel: LocalizedString | null;
  heroLabelRight: LocalizedString | null;
  heroBadge: LocalizedString | null;
  heroHeadline: LocalizedString | null;
  heroHeadlineAccent: LocalizedString | null;
  heroSubtitle: LocalizedText | null;
  pillarsLabel: LocalizedString | null;
  pillarsHeadline: LocalizedString | null;
  pillarsHeadlineAccent: LocalizedString | null;
  pillarCards: Array<{
    title?: LocalizedString;
    description?: LocalizedText;
    icon?:
      | "alertTriangle"
      | "eye"
      | "fileCheck"
      | "lock"
      | "server"
      | "userCheck";
    _key: string;
  }> | null;
  complianceLabel: LocalizedString | null;
  complianceHeadline: LocalizedString | null;
  complianceHeadlineAccent: LocalizedString | null;
  complianceSections: Array<{
    category?: LocalizedString;
    items?: Array<
      {
        _key: string;
      } & LocalizedString
    >;
    _key: string;
  }> | null;
  rightsLabel: LocalizedString | null;
  rightsHeadline: LocalizedString | null;
  rightsHeadlineAccent: LocalizedString | null;
  rightsIntro: LocalizedText | null;
  rightsList: Array<{
    right?: LocalizedString;
    description?: LocalizedText;
    _key: string;
  }> | null;
  dpoTitle: LocalizedString | null;
  dpoSubtitle: LocalizedString | null;
  dpoDescription: LocalizedText | null;
  dpoEmail: string | null;
  ctaHeadline: LocalizedString | null;
  ctaDescription: LocalizedText | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: VIP_PAGE_QUERY
// Query: *[_type == "vipPage"][0]{    // Hero    heroLabel, heroLabelRight, heroHeadline, heroHeadlineAccent, heroStats, heroAnchorText,    heroIntroText, videoLabel, videoText,    // Manifesto    manifestoLabel, manifestoHeadline, manifestoHeadlineAccent,    manifestoQuote, manifestoBody1, manifestoBody2, manifestoMotto, manifestoStats,    // Tiers    tiersLabel, tiersLabelRight, tiersHeadline, tiersDescription, tierCards,    // Steps    stepsLabel, stepsLabelRight, stepsHeadline, steps,    // CTA    ctaCard1Title, ctaCard1Desc, ctaCard2Title, ctaCard2Headline, ctaCard2Sub  }
export type VIP_PAGE_QUERY_RESULT = {
  heroLabel: LocalizedString | null;
  heroLabelRight: LocalizedString | null;
  heroHeadline: LocalizedString | null;
  heroHeadlineAccent: LocalizedString | null;
  heroStats: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }> | null;
  heroAnchorText: LocalizedString | null;
  heroIntroText: LocalizedText | null;
  videoLabel: LocalizedString | null;
  videoText: LocalizedString | null;
  manifestoLabel: LocalizedString | null;
  manifestoHeadline: LocalizedString | null;
  manifestoHeadlineAccent: LocalizedString | null;
  manifestoQuote: LocalizedText | null;
  manifestoBody1: LocalizedText | null;
  manifestoBody2: LocalizedText | null;
  manifestoMotto: LocalizedString | null;
  manifestoStats: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }> | null;
  tiersLabel: LocalizedString | null;
  tiersLabelRight: LocalizedString | null;
  tiersHeadline: LocalizedString | null;
  tiersDescription: LocalizedText | null;
  tierCards: Array<{
    name?: LocalizedString;
    badge?: LocalizedString;
    price?: LocalizedString;
    priceSub?: LocalizedString;
    features?: Array<
      {
        _key: string;
      } & LocalizedString
    >;
    cta?: LocalizedString;
    highlight?: boolean;
    _key: string;
  }> | null;
  stepsLabel: LocalizedString | null;
  stepsLabelRight: LocalizedString | null;
  stepsHeadline: LocalizedString | null;
  steps: Array<{
    step?: string;
    title?: LocalizedString;
    description?: LocalizedText;
    _key: string;
  }> | null;
  ctaCard1Title: LocalizedString | null;
  ctaCard1Desc: LocalizedString | null;
  ctaCard2Title: LocalizedString | null;
  ctaCard2Headline: LocalizedString | null;
  ctaCard2Sub: LocalizedString | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: LEADERSHIP_PAGE_QUERY
// Query: *[_type == "leadershipPage"][0]{    headline, description, teamMembers,    sectionLabel, sectionLabelRight,    ctaHeadline, ctaDescription  }
export type LEADERSHIP_PAGE_QUERY_RESULT = {
  headline: LocalizedString | null;
  description: LocalizedText | null;
  teamMembers: Array<{
    name?: string;
    role?: LocalizedString;
    bio?: LocalizedText;
    linkedin?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }> | null;
  sectionLabel: LocalizedString | null;
  sectionLabelRight: LocalizedString | null;
  ctaHeadline: LocalizedString | null;
  ctaDescription: LocalizedText | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: CAREERS_PAGE_QUERY
// Query: *[_type == "careersPage"][0]{    heroLabel, heroLabelRight,    headline, description,    perks,    openApplicationTitle, openApplicationDesc, formHeadline,    successTitle, successDesc,    ctaHeadline, ctaDescription  }
export type CAREERS_PAGE_QUERY_RESULT = {
  heroLabel: LocalizedString | null;
  heroLabelRight: LocalizedString | null;
  headline: LocalizedString | null;
  description: LocalizedText | null;
  perks: Array<{
    title?: LocalizedString;
    desc?: LocalizedText;
    icon?: string;
    _key: string;
  }> | null;
  openApplicationTitle: LocalizedString | null;
  openApplicationDesc: LocalizedText | null;
  formHeadline: LocalizedString | null;
  successTitle: LocalizedString | null;
  successDesc: LocalizedText | null;
  ctaHeadline: LocalizedString | null;
  ctaDescription: LocalizedText | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: WEBSHOP_PAGE_QUERY
// Query: *[_type == "webshopPage"][0]{    headline, description, merchTitle, merchPendingMessage, quoteTitle, quoteButton  }
export type WEBSHOP_PAGE_QUERY_RESULT = {
  headline: LocalizedString | null;
  description: LocalizedText | null;
  merchTitle: LocalizedString | null;
  merchPendingMessage: LocalizedText | null;
  quoteTitle: LocalizedString | null;
  quoteButton: LocalizedString | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: AI_ASSISTANT_PAGE_QUERY
// Query: *[_type == "aiAssistantPage"][0]{    heroLabel, heroLabelRight,    heroHeadline, heroHeadlineAccent, heroSubtitle,    botTitle, botDescription, botStatus, botLaunchDate,    featuresLabel, featuresHeadline, features,    ctaHeadline, ctaDescription  }
export type AI_ASSISTANT_PAGE_QUERY_RESULT = {
  heroLabel: LocalizedString | null;
  heroLabelRight: LocalizedString | null;
  heroHeadline: LocalizedString | null;
  heroHeadlineAccent: LocalizedString | null;
  heroSubtitle: LocalizedText | null;
  botTitle: LocalizedString | null;
  botDescription: LocalizedText | null;
  botStatus: LocalizedString | null;
  botLaunchDate: LocalizedString | null;
  featuresLabel: LocalizedString | null;
  featuresHeadline: LocalizedString | null;
  features: Array<{
    title?: LocalizedString;
    desc?: LocalizedText;
    icon?: string;
    _key: string;
  }> | null;
  ctaHeadline: LocalizedString | null;
  ctaDescription: LocalizedText | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: FAQ_PAGE_QUERY
// Query: *[_type == "faqPage"][0]{    headline, description, faqs  }
export type FAQ_PAGE_QUERY_RESULT = {
  headline: LocalizedString | null;
  description: LocalizedText | null;
  faqs: Array<{
    question?: LocalizedString;
    answer?: LocalizedText;
    _key: string;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: HELP_CENTER_PAGE_QUERY
// Query: *[_type == "helpCenterPage"][0]{    heroLabel, heroLabelRight,    heroHeadline, heroHeadlineAccent, heroSubtitle,    stats,    channelsLabel, channelsHeadline, channels,    formLabel, formHeadline, formDescription,    contactEmail, contactPhone,    ctaHeadline, ctaDescription  }
export type HELP_CENTER_PAGE_QUERY_RESULT = {
  heroLabel: LocalizedString | null;
  heroLabelRight: LocalizedString | null;
  heroHeadline: LocalizedString | null;
  heroHeadlineAccent: LocalizedString | null;
  heroSubtitle: LocalizedText | null;
  stats: Array<{
    value?: string;
    label?: LocalizedString;
    icon?: string;
    _key: string;
  }> | null;
  channelsLabel: LocalizedString | null;
  channelsHeadline: LocalizedString | null;
  channels: Array<{
    title?: LocalizedString;
    desc?: LocalizedText;
    action?: string;
    href?: string;
    icon?: string;
    _key: string;
  }> | null;
  formLabel: LocalizedString | null;
  formHeadline: LocalizedString | null;
  formDescription: LocalizedText | null;
  contactEmail: string | null;
  contactPhone: string | null;
  ctaHeadline: LocalizedString | null;
  ctaDescription: LocalizedText | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "homePage"][0]{\n    // Navbar\n    navLinks, navCta,\n    // Hero\n    heroBadge, heroHeadline, heroHeadlineAccent, heroSubheadline,\n    heroCta1, heroCta2,\n    // Video\n    videoLabel, videoHeadline, videoHeadlineAccent, videoDescription,\n    // Services\n    servicesLabel, servicesLabelRight, servicesHeadline, servicesDescription,\n    servicesStats, serviceCards, servicesFullserviceTitle, servicesFullserviceDesc,\n    // Country Flags\n    flagsLabel, flagsLabelRight, flagsHeadline, flagsDescription,\n    // Case Stories\n    casesLabel, casesLabelRight, casesHeadline, casesDescription,\n    caseCards, casesCta,\n    // CTA\n    ctaLabel, ctaLabelRight, ctaHeadline, ctaSubheadline,\n    ctaCard1Title, ctaCard1Desc, ctaCard2Title, ctaCard2Headline, ctaCard2Sub,\n    // Newsletter\n    newsletterHeadline, newsletterDescription, newsletterPlaceholder, newsletterButton,\n    // About\n    aboutLabel, aboutHeadline, aboutHeadlineAccent, aboutQuote, aboutBody, aboutBody2, aboutMotto, aboutStats,\n    aboutTeamLabel, aboutTeamIntro, aboutTeam,\n    // FAQ\n    faqHeadline, faqDescription, faqItems, faqCtaText, faqCtaLink,\n    // Request Form\n    formBadge, formHeadline, formHeadlineAccent, formDescription,\n    formButton, formDisclaimer,\n    // Footer\n    footerBrandDesc, footerSocialLabel, footerNewsletterDesc,\n    footerCtaTitle, footerCtaDesc, footerColumns,\n    // Exit Intent\n    exitLabel, exitHeadline, exitHeadlineAccent, exitDescription,\n    exitButton, exitPrivacy,\n    // Globe\n    globeBadge, globeHeadline, globeHeadlineAccent, globeDescription,\n    // Webshop Teaser\n    webshopLabel, webshopLabelRight, webshopHeadline, webshopHeadlineAccent,\n    webshopDescription, webshopComingSoonTitle, webshopComingSoonDesc, webshopCtaText,\n    // Video overlay text\n    videoBottomLabel, videoBottomText\n  }': HOMEPAGE_QUERY_RESULT;
    '*[_type == "aboutPage"][0]{\n    // Hero\n    heroLabel, heroLabelRight, heroHeadline, heroHeadlineAccent, heroHeadlineLine3, heroSubtitle,\n    // Stats\n    stats,\n    // Story\n    storyLabel, storyHeadline, storyHeadlineAccent, storyQuote, storyBody1, storyBody2,\n    // Values\n    valuesLabel, valuesHeadline, valuesHeadlineAccent, valueCards,\n    // Team\n    teamLabel, teamIntro, teamMembers,\n    // CTA\n    ctaHeadline, ctaDescription\n  }': ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "securityPage"][0]{\n    // Hero\n    heroLabel, heroLabelRight, heroBadge, heroHeadline, heroHeadlineAccent, heroSubtitle,\n    // Pillars\n    pillarsLabel, pillarsHeadline, pillarsHeadlineAccent, pillarCards,\n    // Compliance\n    complianceLabel, complianceHeadline, complianceHeadlineAccent, complianceSections,\n    // Rights\n    rightsLabel, rightsHeadline, rightsHeadlineAccent, rightsIntro, rightsList,\n    // DPO\n    dpoTitle, dpoSubtitle, dpoDescription, dpoEmail,\n    // CTA\n    ctaHeadline, ctaDescription\n  }': SECURITY_PAGE_QUERY_RESULT;
    '*[_type == "vipPage"][0]{\n    // Hero\n    heroLabel, heroLabelRight, heroHeadline, heroHeadlineAccent, heroStats, heroAnchorText,\n    heroIntroText, videoLabel, videoText,\n    // Manifesto\n    manifestoLabel, manifestoHeadline, manifestoHeadlineAccent,\n    manifestoQuote, manifestoBody1, manifestoBody2, manifestoMotto, manifestoStats,\n    // Tiers\n    tiersLabel, tiersLabelRight, tiersHeadline, tiersDescription, tierCards,\n    // Steps\n    stepsLabel, stepsLabelRight, stepsHeadline, steps,\n    // CTA\n    ctaCard1Title, ctaCard1Desc, ctaCard2Title, ctaCard2Headline, ctaCard2Sub\n  }': VIP_PAGE_QUERY_RESULT;
    '*[_type == "leadershipPage"][0]{\n    headline, description, teamMembers,\n    sectionLabel, sectionLabelRight,\n    ctaHeadline, ctaDescription\n  }': LEADERSHIP_PAGE_QUERY_RESULT;
    '*[_type == "careersPage"][0]{\n    heroLabel, heroLabelRight,\n    headline, description,\n    perks,\n    openApplicationTitle, openApplicationDesc, formHeadline,\n    successTitle, successDesc,\n    ctaHeadline, ctaDescription\n  }': CAREERS_PAGE_QUERY_RESULT;
    '*[_type == "webshopPage"][0]{\n    headline, description, merchTitle, merchPendingMessage, quoteTitle, quoteButton\n  }': WEBSHOP_PAGE_QUERY_RESULT;
    '*[_type == "aiAssistantPage"][0]{\n    heroLabel, heroLabelRight,\n    heroHeadline, heroHeadlineAccent, heroSubtitle,\n    botTitle, botDescription, botStatus, botLaunchDate,\n    featuresLabel, featuresHeadline, features,\n    ctaHeadline, ctaDescription\n  }': AI_ASSISTANT_PAGE_QUERY_RESULT;
    '*[_type == "faqPage"][0]{\n    headline, description, faqs\n  }': FAQ_PAGE_QUERY_RESULT;
    '*[_type == "helpCenterPage"][0]{\n    heroLabel, heroLabelRight,\n    heroHeadline, heroHeadlineAccent, heroSubtitle,\n    stats,\n    channelsLabel, channelsHeadline, channels,\n    formLabel, formHeadline, formDescription,\n    contactEmail, contactPhone,\n    ctaHeadline, ctaDescription\n  }': HELP_CENTER_PAGE_QUERY_RESULT;
  }
}
